const express= require("express");
const router= express.Router();
router.use(express.urlencoded({extended:true}));
router.use(express.json());
const isAuthenticated= require("../middlewares/isLoggedIn.js");
const owner= require("../middlewares/isOwner.js");
const {getAllProducts, getProductById, addProduct, updateProduct, deleteProduct}=require("../controllers/productController.js");
router.get("/", getAllProducts);
router.get("/:id", getProductById);
router.post('/', isAuthenticated, addProduct);
router.put('/:id', isAuthenticated, owner, updateProduct);
router.delete('/:id', isAuthenticated, owner, deleteProduct);
module.exports=router;